In [1]:
import theano
from theano import tensor as T, function
import numpy as np

# Function definitions

In [5]:
X = T.matrix('x')
Y = X**2
Z = T.grad(Y.sum(), X)
F = function([X], [Y, Z])

In [6]:
x = np.ones((2, 2))*3
y, z = F(x)

# Print results

In [7]:
print(x)
print('_'*20)
print(y)
print('_'*20)
print(z)

[[ 3.  3.]
 [ 3.  3.]]
____________________
[[ 9.  9.]
 [ 9.  9.]]
____________________
[[ 6.  6.]
 [ 6.  6.]]
